{
 "title": "ST-BNG3",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {
     "query": "label_values(system_cpu_summary_total_cpu_usage,source)"
    }
   },
   {
    "name": "iface",
    "query": {
     "query": "label_values(port_ethernet_statistics_in_octets{source=\"$device\"},port_port_id)"
    }
   },
   {
    "name": "device_traffic",
    "query": {
     "query": "label_values(port_statistics_in_octets,source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$iface traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(port_statistics_in_unicast_packets{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Unicast In"
    },
    {
     "expr": "rate(port_statistics_in_broadcast_packets{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Broadcast In"
    },
    {
     "expr": "rate(port_statistics_in_errors{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Errors In"
    },
    {
     "expr": "rate(port_statistics_in_discards{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Discards In"
    },
    {
     "expr": "rate(port_statistics_out_unicast_packets{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Unicast Out"
    },
    {
     "expr": "rate(port_statistics_out_broadcast_packets{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Broadcast Out"
    },
    {
     "expr": "rate(port_statistics_out_multicast_packets{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Multicast Out"
    },
    {
     "expr": "rate(port_statistics_out_errors{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Errors Out"
    },
    {
     "expr": "rate(port_statistics_out_discards{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Discards Out"
    },
    {
     "expr": "rate(port_statistics_in_multicast_packets{source=\"$device\", port_port_id=\"$iface\"}[$__rate_interval])",
     "legendFormat": "Multicast In"
    }
   ]
  },
  {
   "title": "Subscriber Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value > 0",
     "legendFormat": " {{source}} active "
    }
   ]
  },
  {
   "title": "Peak Subscriber Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_peak_value{source=\"$device\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "CPU_usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Memory Pool",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_total_in_use",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "$device Port Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_oper_state{source=\"$device\"}",
     "legendFormat": "{{port_port_id}}"
    }
   ]
  },
  {
   "title": "$device L2 Port Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(port_statistics_in_octets{source=\"$device\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{port_port_id}} in"
    },
    {
     "expr": "-rate(port_statistics_out_octets{source=\"$device\"}[$__rate_interval])*8 >0 ",
     "legendFormat": "{{port_port_id}} out"
    }
   ]
  },
  {
   "title": "$device CPU Utilization Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\", source=\"$device\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "$device IP Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(router_interface_statistics_ip_in_octets{source=\"$device\"}[$__interval])*8",
     "legendFormat": "{{port_port_id}} in"
    },
    {
     "expr": "-rate(router_interface_statistics_ip_out_octets{source=\"$device\"}[$__interval])*8 ",
     "legendFormat": "{{port_port_id}} out"
    }
   ]
  },
  {
   "title": "Memory utilization Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_available_memory{source=\"$device\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "-1*system_memory_pools_summary_total_in_use{source=\"$device\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Port_statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(\r\n  port_ethernet_statistics_in_octets{\r\n    source=\"100.127.188.89\",\r\n    port_port_id=\"1/1/c18/1\"\r\n  }[1m]\r\n)",
     "legendFormat": "{{source}} / {{port_port_id}}"
    }
   ]
  },
  {
   "title": "IPv6 Hosts Current",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_ipv6_hosts_current_value",
     "legendFormat": "{{ family }} {{ protocol }} "
    }
   ]
  },
  {
   "title": "$device Route Table",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_route_table_unicast_active_routes{source=\"$device\", router_router_name=\"Base\"}",
     "legendFormat": "{{ family }} {{ protocol }} "
    }
   ]
  },
  {
   "title": "Interface Traffic Rates-IN",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(port_statistics_in_octets[1m]) > 0 ",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "DHCP Declined Addresses",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_peak_value",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "IPv4 Hosts Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_ipv4_hosts_current_value > 0",
     "legendFormat": "{{counter}} - {{source}}"
    }
   ]
  },
  {
   "title": "DHCP Provisioned Addresses",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 7, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_vprn_dhcp_server_dhcpv4_pool_statistics_local_provisioned_addresses{instance=~\".*\"}",
     "legendFormat": "{{instance}} - {{service_name}} - {{name}} - {{pool_name}}"
    }
   ]
  },
  {
   "title": "DHCP Free Addresses",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 5, "x": 7, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_vprn_dhcp_server_dhcpv4_pool_statistics_local_free_addresses",
     "legendFormat": "{{pool_pool_name}} - {{source}}"
    }
   ]
  },
  {
   "title": "SLA Packet Drops",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_subscriber_sla_profile_instance_egress_qos_queue_statistics_profile_out_exceed_profile_dropped_packets",
     "legendFormat": "{{queue_id}} - {{subscriber_id}}"
    }
   ]
  },
  {
   "title": "MDA Temperature\t",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "card_mda_hardware_data_temperature",
     "legendFormat": "{{card_slot_number}}/{{mda_mda_slot}}-{{source}}"
    }
   ]
  },
  {
   "title": "Interface Status + Rate (Bps)  ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(\r\n  port_ethernet_statistics_in_octets{\r\n    source=~\"100.127.188.89|100.127.188.90\",\r\n    port_port_id=~\"1/1/c1/1|1/1/c18/1\"\r\n  }[1m]\r\n)",
     "legendFormat": "{{source}} / {{port_port_id}}"
    }
   ]
  },
  { "title": "Monitor-2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } }
 ]
}